defaultSemverRangePrefix: ""

nodeLinker: pnp

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      "typescript": "^4.3.5"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
