defaultSemverRangePrefix: ""

nodeLinker: pnp

pnpEnableEsmLoader: true

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
